//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int AccountId { get; set; }
        public int BookId { get; set; }
        public DateTime ReservationDate { get; set; }
        public int Quantity { get; set; }
        public string BorrowersName { get; set; }
        public string BookTitle { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Book Book { get; set; }
    }
}
